apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hgkp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0014-tenant/tkrw-pr712-0075-0014-app/devfile-sample-hgkp@sha256:ee2d83d21322c044cc7d2f5031bb471052b6ef1729d8542e06f9b071e3f013c7
        name: my-nodejs
        resources: {}
status: {}
